services:
  rustmap3d-dev:
    image: rustmap3d:latest
    build:
      context: ../
      args: &default-args
        - UID
        - GID
        - USER=rust

    working_dir: /home/rust/rustmap3d
    network_mode: host
    user: $UID:$GID
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/home/rust/rustmap3d:rw
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh/:/home/rust/.ssh/
