[package]
name = "map3d"
version = "0.1.1"
edition = "2021"

[dependencies]
glam = "0.29"
almost = "0.2.0"
rand = "0.9"
chrono = "0.4.38"

[dev-dependencies]
rstest = "0.25"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "geobench"
harness = false