[package]
name = "map3d"
version = "0.1.1"
edition = "2021"

[dependencies]
glam = "~0"
almost = "~0.2"
rand = "~0.9"
chrono = "~0.4"

[dev-dependencies]
rstest = "0.26"
criterion = { version = "~0.8", features = ["html_reports"] }

[[bench]]
name = "geobench"
harness = false
